// <auto-generated-bridge />
// -----------------------------------------------------------------------
// MIGRATION BRIDGE — HyPlayListFacade
// -----------------------------------------------------------------------
// This static class mirrors the public API surface of HyPlayList but
// delegates every call to the new DI-based services (IPlaylistService,
// IPlaybackControlService, ILyricService, etc.).
//
// PURPOSE:
//   Allow existing consumers that reference HyPlayList.* to be migrated
//   one call-site at a time.  Once every consumer has been updated to
//   inject the service interfaces directly, this file should be DELETED.
//
// DO NOT add new business logic here — only thin delegation.
// -----------------------------------------------------------------------

#region

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.DependencyInjection;
using CommunityToolkit.Mvvm.Messaging;
using HyPlayer.Classes;
using HyPlayer.Services.Abstractions;
using HyPlayer.Services.Playback;
using HyPlayer.Services.Playback.Messages;
using HyPlayer.UWP.Chopin;
using HyPlayer.UWP.Chopin.Abstractions.Models;

#endregion

namespace HyPlayer.HyPlayControl;

/// <summary>
/// Migration bridge: provides the same static API surface as
/// <see cref="HyPlayList"/> but delegates to the new DI-based services.
/// <para>
/// <b>This class is temporary.</b> Remove it once all consumers have been
/// migrated to constructor-inject the service interfaces directly.
/// </para>
/// </summary>
public static class HyPlayListFacade
{
    // ---------------------------------------------------------------
    //  Lazy service accessors — resolved once from Ioc.Default
    // ---------------------------------------------------------------

    private static IPlaylistService? _playlistService;
    private static IPlaybackControlService? _playbackControlService;
    private static ILyricService? _lyricService;
    private static IPlaybackNotificationService? _notificationService;
    private static PlaybackStateService? _stateService;
    private static AudioGraphPlayer? _player;

    private static IPlaylistService PlaylistService
        => _playlistService ??= Ioc.Default.GetRequiredService<IPlaylistService>();

    private static IPlaybackControlService PlaybackControlService
        => _playbackControlService ??= Ioc.Default.GetRequiredService<IPlaybackControlService>();

    private static ILyricService LyricService
        => _lyricService ??= Ioc.Default.GetRequiredService<ILyricService>();

    private static IPlaybackNotificationService NotificationService
        => _notificationService ??= Ioc.Default.GetRequiredService<IPlaybackNotificationService>();

    private static PlaybackStateService StateService
        => _stateService ??= Ioc.Default.GetRequiredService<PlaybackStateService>();

    /// <summary>
    /// Low-level player access. Prefer <see cref="PlaybackControlService"/>
    /// for high-level operations.
    /// </summary>
    public static AudioGraphPlayer Player
        => _player ??= Ioc.Default.GetRequiredService<AudioGraphPlayer>();

    // ---------------------------------------------------------------
    //  Properties — mapped to new services
    // ---------------------------------------------------------------

    /// <summary>Current playlist items (read-only view).</summary>
    public static IReadOnlyList<HyPlayItem> List => PlaylistService.Items;

    /// <summary>Index of the currently playing item.</summary>
    public static int NowPlaying
    {
        get => PlaylistService.NowPlayingIndex;
        // Setter kept for back-compat; new code should not set this directly.
        set { /* no-op — index is managed by IPlaylistService */ }
    }

    /// <summary>Currently playing item, or <c>null</c>.</summary>
    public static HyPlayItem? NowPlayingItem => PlaylistService.NowPlayingItem;

    /// <summary>Whether audio is currently playing.</summary>
    public static bool IsPlaying => PlaybackControlService.IsPlaying;

    /// <summary>
    /// Current play mode mapped from the active strategy Id.
    /// </summary>
    public static PlayMode NowPlayType => StateService.ActiveStrategyId switch
    {
        "sgl" => PlayMode.SinglePlay,
        "shf" or "shn" => PlayMode.Shuffled,
        _ => PlayMode.DefaultRoll // "seq" and any unknown
    };

    /// <summary>Output volume (0.0 – 1.0).</summary>
    public static double PlayerOutgoingVolume
    {
        get => PlaybackControlService.Volume;
        set => PlaybackControlService.Volume = value;
    }

    /// <summary>Current lyric info.</summary>
    public static HyLyricInfo HyLyricInfo => LyricService.CurrentLyricInfo;

    /// <summary>Current lyric line index.</summary>
    public static int LyricPos => LyricService.CurrentLyricIndex;

    /// <summary>Play source identifier (for history, etc.).</summary>
    public static string PlaySourceId
    {
        get => PlaylistService.PlaySourceId;
        set => PlaylistService.PlaySourceId = value;
    }

    // ---------------------------------------------------------------
    //  Methods — thin delegation
    // ---------------------------------------------------------------

    /// <summary>Initialize the playback engine.</summary>
    public static async void InitializeHyPlaylist()
    {
        await PlaybackControlService.InitializeAsync();
    }

    /// <summary>Move to the next track.</summary>
    public static async void SongMoveNext()
    {
        await PlaylistService.MoveNextAsync(userInitiated: true);
    }

    /// <summary>Move to the previous track.</summary>
    public static async void SongMovePrevious()
    {
        await PlaylistService.MovePreviousAsync();
    }

    /// <summary>Jump to a specific item in the playlist.</summary>
    public static async void SongMoveTo(HyPlayItem item)
    {
        await PlaylistService.MoveToAsync(item);
    }

    /// <summary>Clear the entire playlist.</summary>
    public static void RemoveAllSong()
    {
        PlaylistService.Clear();
    }

    /// <summary>Remove a song at the given index.</summary>
    public static void RemoveSong(int index)
    {
        PlaylistService.RemoveAt(index);
    }

    /// <summary>Seek to a specific position.</summary>
    public static async void Seek(TimeSpan targetTimeSpan)
    {
        await PlaybackControlService.SeekAsync(targetTimeSpan);
    }

    /// <summary>
    /// Change the play mode (DefaultRoll / SinglePlay / Shuffled).
    /// Maps the <see cref="PlayMode"/> enum to the three-letter strategy Id
    /// used by <see cref="IPlaylistService"/>.
    /// </summary>
    public static void ChangePlayMode(PlayMode playMode)
    {
        var strategyId = playMode switch
        {
            PlayMode.DefaultRoll => "seq",
            PlayMode.SinglePlay => "sgl",
            PlayMode.Shuffled => "shn", // default to no-repeat shuffle
            _ => "seq"
        };
        PlaylistService.SetStrategy(strategyId);
    }

    /// <summary>Load a media source and optionally start playback.</summary>
    public static async Task LoadMediaSource(HyPlayItem item, bool setAsPrimary = true, bool autoPlay = true)
    {
        await PlaybackControlService.LoadAndPlayAsync(item, setAsPrimary, autoPlay);
    }

    /// <summary>
    /// Build a <see cref="HyPlayItem"/> from an <see cref="NCSong"/> and
    /// append it to the playlist.
    /// </summary>
    public static HyPlayItem AppendNcSong(NCSong ncSong, int position = -1)
    {
        var hpi = PlaylistService.NCSongToPlayItem(ncSong);
        PlaylistService.AppendItem(hpi, position);
        return hpi;
    }

    /// <summary>Notify that a batch append operation has completed.</summary>
    public static void SongAppendDone(bool isShuffleTrigger = false)
    {
        PlaylistService.NotifyAppendDone(isShuffleTrigger);
    }

    /// <summary>
    /// Like / unlike the current song. This is not part of the playback
    /// core — delegates to the existing <see cref="HyPlayList.LikeSong"/>
    /// implementation.
    /// </summary>
    public static void LikeSong()
    {
        HyPlayList.LikeSong();
    }

    // ---------------------------------------------------------------
    //  Events — pass-through via WeakReferenceMessenger
    // ---------------------------------------------------------------
    //
    //  Old consumers subscribe to these static events.  We bridge them
    //  by listening to the corresponding Messenger messages and firing
    //  the delegates.  This keeps old UI code working during migration.
    //
    //  NOTE: Event subscriptions are intentionally one-way (message →
    //  delegate).  New code should subscribe to messages directly.
    // ---------------------------------------------------------------

    /// <summary>Fired when the playlist content changes.</summary>
    public static event HyPlayList.PlayListAddDoneEvent? OnPlayListAddDone;

    /// <summary>Fired when a seek is requested.</summary>
    public static event HyPlayList.ManualSeekEvent? OnManualSeek;

    /// <summary>Fired when the like status changes.</summary>
    public static event HyPlayList.SongLikeStatusChanged? OnSongLikeStatusChange;

    /// <summary>Fired when the cover image changes.</summary>
    public static event HyPlayList.SongCoverChanged? OnSongCoverChanged;

    /// <summary>Fired when lyrics finish loading.</summary>
    public static event HyPlayList.LyricLoadedEvent? OnLyricLoaded;

    /// <summary>Fired when the lyric color changes.</summary>
    public static event HyPlayList.LyricColorChangeEvent? OnLyricColorChange;

    /// <summary>
    /// Call once at startup to wire Messenger messages to the legacy
    /// static events above.
    /// </summary>
    public static void RegisterMessageBridge()
    {
        var messenger = WeakReferenceMessenger.Default;

        messenger.Register<PlaylistChangedMessage>(typeof(HyPlayListFacade),
            (_, m) => OnPlayListAddDone?.Invoke(m.IsShuffleTrigger));

        messenger.Register<SeekRequestedMessage>(typeof(HyPlayListFacade),
            (_, m) => OnManualSeek?.Invoke(m.Position));

        messenger.Register<SongLikeStatusChangedMessage>(typeof(HyPlayListFacade),
            (_, m) => OnSongLikeStatusChange?.Invoke(m.IsLiked));

        messenger.Register<CoverChangedMessage>(typeof(HyPlayListFacade),
            (_, m) => OnSongCoverChanged?.Invoke(m.Item));

        messenger.Register<LyricLoadedMessage>(typeof(HyPlayListFacade),
            (_, m) => OnLyricLoaded?.Invoke());

        messenger.Register<LyricColorChangedMessage>(typeof(HyPlayListFacade),
            (_, _) => OnLyricColorChange?.Invoke());
    }

    /// <summary>
    /// Unregister all message-to-event bridges. Call on shutdown or when
    /// the facade is no longer needed.
    /// </summary>
    public static void UnregisterMessageBridge()
    {
        WeakReferenceMessenger.Default.UnregisterAll(typeof(HyPlayListFacade));
    }
}
