<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<Platforms>x64;arm64</Platforms>
		<UseUwp>true</UseUwp>

	</PropertyGroup>

	<PropertyGroup>
		<CsWinRTIncludes>Microsoft.Gaming.XboxGameBar</CsWinRTIncludes>
	</PropertyGroup>

	<ItemGroup>
		<CsWinRTInputs Include="$(PkgMicrosoft_Gaming_XboxGameBar)\lib\uap10.0\Microsoft.Gaming.XboxGameBar.winmd" />
		<CsWinRTInputs Include="$(PkgMicrosoft_Gaming_XboxGameBar)\private\Microsoft.Gaming.XboxGameBar.Private.winmd" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Gaming.XboxGameBar" Version="7.3.2506120" GeneratePathProperty="true">
			<ExcludeAssets>all</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(PkgMicrosoft_Gaming_XboxGameBar)\runtimes\win10-$(Platform)\native\Microsoft.Gaming.XboxGameBar.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(PkgMicrosoft_Gaming_XboxGameBar)\lib\uap10.0\Microsoft.Gaming.XboxGameBar.winmd">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="$(PkgMicrosoft_Gaming_XboxGameBar)\private\Microsoft.Gaming.XboxGameBar.Private.winmd">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="$(PkgMicrosoft_Gaming_XboxGameBar)\runtimes\win10-$(Platform)\native\Microsoft.Gaming.XboxGameBar.pri" />
	</ItemGroup>
	
</Project>
